# SCSS Linter configuration and overrides
# (some of the rules are rules are too.. evangelical)
#
linters:
  # Spaces - 2
  Indentation:
    enabled: true
    character: space
    width: 2

  # Property sort order - recess (twitter / bootstrap style)
  PropertySortOrder:
    order: recess

  # Stricter warnings against @extend because they're bad news
  PlaceholderInExtend:
    enabled: false
  ExtendDirective:
    enabled: true

  # Allow /* */ style comments because they're legit
  Comment:
    enabled: false

  # Allow empty lines between { } for brevity
  EmptyLineBetweenBlocks:
    enabled: false

  # Allow space after property: for alignment
  SpaceAfterPropertyColon:
    enabled: false

  # Allow color keywords and literals because they're perfectly fine
  ColorKeyword:
    enabled: false
  ColorVariable:
    enabled: false
